//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnadoluRentalWeb.AnadoluRentalKullaniciService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanici", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Kullanici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int kullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullSifreField;
        
        private System.Nullable<int> kullRolIDField;
        
        private System.Nullable<int> kullSirketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnadoluRentalWeb.AnadoluRentalKullaniciService.Rol RolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int kullaniciID {
            get {
                return this.kullaniciIDField;
            }
            set {
                if ((this.kullaniciIDField.Equals(value) != true)) {
                    this.kullaniciIDField = value;
                    this.RaisePropertyChanged("kullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string kullAdi {
            get {
                return this.kullAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.kullAdiField, value) != true)) {
                    this.kullAdiField = value;
                    this.RaisePropertyChanged("kullAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string kullSifre {
            get {
                return this.kullSifreField;
            }
            set {
                if ((object.ReferenceEquals(this.kullSifreField, value) != true)) {
                    this.kullSifreField = value;
                    this.RaisePropertyChanged("kullSifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> kullRolID {
            get {
                return this.kullRolIDField;
            }
            set {
                if ((this.kullRolIDField.Equals(value) != true)) {
                    this.kullRolIDField = value;
                    this.RaisePropertyChanged("kullRolID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> kullSirketID {
            get {
                return this.kullSirketIDField;
            }
            set {
                if ((this.kullSirketIDField.Equals(value) != true)) {
                    this.kullSirketIDField = value;
                    this.RaisePropertyChanged("kullSirketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TelNo {
            get {
                return this.TelNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNoField, value) != true)) {
                    this.TelNoField = value;
                    this.RaisePropertyChanged("TelNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.Rol Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Rol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int rolIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rolAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int rolID {
            get {
                return this.rolIDField;
            }
            set {
                if ((this.rolIDField.Equals(value) != true)) {
                    this.rolIDField = value;
                    this.RaisePropertyChanged("rolID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rolAdi {
            get {
                return this.rolAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.rolAdiField, value) != true)) {
                    this.rolAdiField = value;
                    this.RaisePropertyChanged("rolAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnadoluRentalKullaniciService.KullaniciWebServiceSoap")]
    public interface KullaniciWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name kull from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciEkle", ReplyAction="*")]
        AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleResponse KullaniciEkle(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleResponse> KullaniciEkleAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequest request);
        
        // CODEGEN: Generating message contract since element name kull from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciGuncelle", ReplyAction="*")]
        AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleResponse KullaniciGuncelle(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleResponse> KullaniciGuncelleAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciSilById", ReplyAction="*")]
        bool KullaniciSilById(int kullID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciSilById", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> KullaniciSilByIdAsync(int kullID);
        
        // CODEGEN: Generating message contract since element name SelectAllKullaniciResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllKullanici", ReplyAction="*")]
        AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciResponse SelectAllKullanici(AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllKullanici", ReplyAction="*")]
        System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciResponse> SelectAllKullaniciAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequest request);
        
        // CODEGEN: Generating message contract since element name KullaniciSecByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciSecById", ReplyAction="*")]
        AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdResponse KullaniciSecById(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciSecById", ReplyAction="*")]
        System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdResponse> KullaniciSecByIdAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciEkle", Namespace="http://tempuri.org/", Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequestBody Body;
        
        public KullaniciEkleRequest() {
        }
        
        public KullaniciEkleRequest(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici kull;
        
        public KullaniciEkleRequestBody() {
        }
        
        public KullaniciEkleRequestBody(AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici kull) {
            this.kull = kull;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleResponseBody Body;
        
        public KullaniciEkleResponse() {
        }
        
        public KullaniciEkleResponse(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool KullaniciEkleResult;
        
        public KullaniciEkleResponseBody() {
        }
        
        public KullaniciEkleResponseBody(bool KullaniciEkleResult) {
            this.KullaniciEkleResult = KullaniciEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequestBody Body;
        
        public KullaniciGuncelleRequest() {
        }
        
        public KullaniciGuncelleRequest(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici kull;
        
        public KullaniciGuncelleRequestBody() {
        }
        
        public KullaniciGuncelleRequestBody(AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici kull) {
            this.kull = kull;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleResponseBody Body;
        
        public KullaniciGuncelleResponse() {
        }
        
        public KullaniciGuncelleResponse(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciGuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool KullaniciGuncelleResult;
        
        public KullaniciGuncelleResponseBody() {
        }
        
        public KullaniciGuncelleResponseBody(bool KullaniciGuncelleResult) {
            this.KullaniciGuncelleResult = KullaniciGuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllKullaniciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllKullanici", Namespace="http://tempuri.org/", Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequestBody Body;
        
        public SelectAllKullaniciRequest() {
        }
        
        public SelectAllKullaniciRequest(AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllKullaniciRequestBody {
        
        public SelectAllKullaniciRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllKullaniciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllKullaniciResponse", Namespace="http://tempuri.org/", Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciResponseBody Body;
        
        public SelectAllKullaniciResponse() {
        }
        
        public SelectAllKullaniciResponse(AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllKullaniciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici[] SelectAllKullaniciResult;
        
        public SelectAllKullaniciResponseBody() {
        }
        
        public SelectAllKullaniciResponseBody(AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici[] SelectAllKullaniciResult) {
            this.SelectAllKullaniciResult = SelectAllKullaniciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciSecByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciSecById", Namespace="http://tempuri.org/", Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequestBody Body;
        
        public KullaniciSecByIdRequest() {
        }
        
        public KullaniciSecByIdRequest(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciSecByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public KullaniciSecByIdRequestBody() {
        }
        
        public KullaniciSecByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciSecByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciSecByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdResponseBody Body;
        
        public KullaniciSecByIdResponse() {
        }
        
        public KullaniciSecByIdResponse(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciSecByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici KullaniciSecByIdResult;
        
        public KullaniciSecByIdResponseBody() {
        }
        
        public KullaniciSecByIdResponseBody(AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici KullaniciSecByIdResult) {
            this.KullaniciSecByIdResult = KullaniciSecByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KullaniciWebServiceSoapChannel : AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KullaniciWebServiceSoapClient : System.ServiceModel.ClientBase<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap>, AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap {
        
        public KullaniciWebServiceSoapClient() {
        }
        
        public KullaniciWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KullaniciWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleResponse AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap.KullaniciEkle(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequest request) {
            return base.Channel.KullaniciEkle(request);
        }
        
        public bool KullaniciEkle(AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici kull) {
            AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequest inValue = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequest();
            inValue.Body = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequestBody();
            inValue.Body.kull = kull;
            AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleResponse retVal = ((AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap)(this)).KullaniciEkle(inValue);
            return retVal.Body.KullaniciEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleResponse> AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap.KullaniciEkleAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequest request) {
            return base.Channel.KullaniciEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleResponse> KullaniciEkleAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici kull) {
            AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequest inValue = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequest();
            inValue.Body = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciEkleRequestBody();
            inValue.Body.kull = kull;
            return ((AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap)(this)).KullaniciEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleResponse AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap.KullaniciGuncelle(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequest request) {
            return base.Channel.KullaniciGuncelle(request);
        }
        
        public bool KullaniciGuncelle(AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici kull) {
            AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequest inValue = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequest();
            inValue.Body = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequestBody();
            inValue.Body.kull = kull;
            AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleResponse retVal = ((AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap)(this)).KullaniciGuncelle(inValue);
            return retVal.Body.KullaniciGuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleResponse> AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap.KullaniciGuncelleAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequest request) {
            return base.Channel.KullaniciGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleResponse> KullaniciGuncelleAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici kull) {
            AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequest inValue = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequest();
            inValue.Body = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciGuncelleRequestBody();
            inValue.Body.kull = kull;
            return ((AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap)(this)).KullaniciGuncelleAsync(inValue);
        }
        
        public bool KullaniciSilById(int kullID) {
            return base.Channel.KullaniciSilById(kullID);
        }
        
        public System.Threading.Tasks.Task<bool> KullaniciSilByIdAsync(int kullID) {
            return base.Channel.KullaniciSilByIdAsync(kullID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciResponse AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap.SelectAllKullanici(AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequest request) {
            return base.Channel.SelectAllKullanici(request);
        }
        
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici[] SelectAllKullanici() {
            AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequest inValue = new AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequest();
            inValue.Body = new AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequestBody();
            AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciResponse retVal = ((AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap)(this)).SelectAllKullanici(inValue);
            return retVal.Body.SelectAllKullaniciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciResponse> AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap.SelectAllKullaniciAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequest request) {
            return base.Channel.SelectAllKullaniciAsync(request);
        }
        
        public System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciResponse> SelectAllKullaniciAsync() {
            AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequest inValue = new AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequest();
            inValue.Body = new AnadoluRentalWeb.AnadoluRentalKullaniciService.SelectAllKullaniciRequestBody();
            return ((AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap)(this)).SelectAllKullaniciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdResponse AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap.KullaniciSecById(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequest request) {
            return base.Channel.KullaniciSecById(request);
        }
        
        public AnadoluRentalWeb.AnadoluRentalKullaniciService.Kullanici KullaniciSecById(int id) {
            AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequest inValue = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequest();
            inValue.Body = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequestBody();
            inValue.Body.id = id;
            AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdResponse retVal = ((AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap)(this)).KullaniciSecById(inValue);
            return retVal.Body.KullaniciSecByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdResponse> AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap.KullaniciSecByIdAsync(AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequest request) {
            return base.Channel.KullaniciSecByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdResponse> KullaniciSecByIdAsync(int id) {
            AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequest inValue = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequest();
            inValue.Body = new AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciSecByIdRequestBody();
            inValue.Body.id = id;
            return ((AnadoluRentalWeb.AnadoluRentalKullaniciService.KullaniciWebServiceSoap)(this)).KullaniciSecByIdAsync(inValue);
        }
    }
}
