//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnadoluRental.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arac()
        {
            this.Kiralik = new HashSet<Kiralik>();
        }
    
        public int aracID { get; set; }
        public string aracMarka { get; set; }
        public string aracModel { get; set; }
        public Nullable<int> gerekenEhliyetYasi { get; set; }
        public Nullable<int> minYasSiniri { get; set; }
        public Nullable<int> gunlukSinirKM { get; set; }
        public Nullable<int> aracKM { get; set; }
        public Nullable<int> airBagSayisi { get; set; }
        public Nullable<int> bagacHacmi { get; set; }
        public Nullable<int> koltukSayisi { get; set; }
        public Nullable<int> gunlukKiralikFiyati { get; set; }
        public int aitOlduguSirketID { get; set; }
    
        public virtual Sirket Sirket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiralik> Kiralik { get; set; }
    }
}
