//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnadoluRental.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralik
    {
        public int kiraID { get; set; }
        public int kiralananAracID { get; set; }
        public Nullable<System.DateTime> kiraTarihi { get; set; }
        public Nullable<int> verilisKM { get; set; }
        public Nullable<int> kiraBitisKM { get; set; }
        public Nullable<int> kiraAlinanUcret { get; set; }
        public int kiralayanKulID { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
